language: python

python:
 - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install -U pip"
  - "pip install psycopg2-binary"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
 
script: 
  - nosetests --with-coverage 
 
after_success:
  - "coveralls"