language: python

python:
 - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install -U pip"
  - "python setup.py install"
  - "pip install psycopg2-binary"
  
 
script: 
  - nosetests --with-coverage --cover-package app 
 
after_success:
  - "coveralls"