language: python

python:
 - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install psycopg2-binary"
 
script: 
  - nosetests --with-coverage --cover-erase --cover-package=api/ && coverage report
 
after_success:
  - "coveralls"